### ISSUE TITLE
如何显示api返回的内容？

### ISSUE THREAD

**Issue by HANDSOMEskuld** [ChenYFan/Dujitang#1]
你好，小白请教：如何显示调用其他网站api返回的内容？可否添加此功能呢？比如调用其它网站api随机显示一句诗词。谢谢

**Comment by ChenYFan** [comment]
Repo主表示十分无奈，请稍等repo主给你带来的完整解释

**Comment by ChenYFan** [comment]
1.我这个PHP是官方nows去除数据库后完整本地化简化版，除了通过document.write输出,没有其它输出方法

**Comment by ChenYFan** [comment]
2.调用其它网站api接口,repo主表示能力有限,建议你去看看其他网站的官方说明,我的php没有调用其它网站的意图

**Comment by ChenYFan** [comment]
3.随机输出诗词:打开data.dat,一行一句古诗词,接口不变,即可输出随机显示一句诗词

**Comment by ChenYFan** [comment]
4.我觉得你可能把我repo的意图想错了,我这个repo纯粹是实现随机读取一行文本的php代码,没有意思说调用其它网站的接口.感谢你的issues,不过调用别站api请阅读站点api使用手册,本repo没有需求、也不需要接入其它api，请悉知，谢谢。
